version: "3.8"
services:
  oengus_patreon:
    container_name: oengus-patreon
    build:
      context: .
    volumes:
      - credentials:/storage/oengus-patreon
    ports:
      - "9000:9000"
    network_mode: "bridge"
    environment:
      - PATREON_CAMPAIGN_ID=5872382
      - PATREON_CLIENT_ID=
      - PATREON_CLIENT_SECRET=
      - PATREON_WEBHOOK_SECRET=
      - OENGUS_BASE=https://oengus.io
volumes:
  credentials:
