name: Publish Development Docker Image
on:
    push:
        branches: [master]
jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                submodules: true
            - name: Push oengusdotdev to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: docker.pkg.github.com
                repository: esamarathon/oengus-patron-fetcher/patron-fetcher
                tags: latest
                # we're doing manual updates
#            - name: Trigger dev webhook
#              uses: zzzze/webhook-trigger@v1.0.0
#              with:
#                webhook_url: ${{ secrets.DEV_WEBHOOK_URL }}
